export AURIUM_PUBLIC_KEY=
export AURIUM_PRIVATE_KEY=
export AURIUM_NODE_URL=http://192.168.8.133:7545
export AURIUM_CONTRACT_ADDRESS=

#unset AURIUM_PUBLIC_KEY AURIUM_PRIVATE_KEY AURIUM_NODE_URL AURIUM_CONTRACT_ADDRESS
